services:
  app:
    build: 
      context: .
      target: builder
    container_name: socialpulse-app-dev
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy port
    env_file:
      - .env
    environment:
      - DEBUG=true
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - socialpulse-network

  db:
    image: postgres:15-alpine
    container_name: socialpulse-db-dev
    ports:
      - "5432:5432"  # Expose for direct access
    env_file:
      - .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - socialpulse-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: socialpulse-redis-dev
    ports:
      - "6379:6379"  # Expose for direct access
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - socialpulse-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build: 
      context: .
      target: builder
    container_name: socialpulse-worker-dev
    command: celery -A app.infrastructure.background_tasks.celery_app worker --loglevel=debug --concurrency=1
    env_file:
      - .env
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - socialpulse-network

  beat:
    build: 
      context: .
      target: builder
    container_name: socialpulse-beat-dev
    command: celery -A app.infrastructure.background_tasks.celery_app beat --loglevel=debug
    env_file:
      - .env
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - socialpulse-network

  # Optional development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: socialpulse-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@socialpulse.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - socialpulse-network
    profiles:
      - tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: socialpulse-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - socialpulse-network
    profiles:
      - tools

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  socialpulse-network:
    driver: bridge
